//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqcosApp.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeqcosApp.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to auto-detect the format of your file..
        /// </summary>
        public static string AutoDetectFail {
            get {
                return ResourceManager.GetString("AutoDetectFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniVec.
        /// </summary>
        public static string BLAST_DB_DEFAULT {
            get {
                return ResourceManager.GetString("BLAST_DB_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blast_formatter.exe.
        /// </summary>
        public static string BLAST_FORMATTER {
            get {
                return ResourceManager.GetString("BLAST_FORMATTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1000000.
        /// </summary>
        public static string BLAST_MAX_SEQUENCES_DEFAULT {
            get {
                return ResourceManager.GetString("BLAST_MAX_SEQUENCES_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11.
        /// </summary>
        public static string BLAST_OUTPUT_FORMAT {
            get {
                return ResourceManager.GetString("BLAST_OUTPUT_FORMAT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blast.asn.
        /// </summary>
        public static string BLAST_OUTPUT_SUFFIX_ASN {
            get {
                return ResourceManager.GetString("BLAST_OUTPUT_SUFFIX_ASN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blast.out.
        /// </summary>
        public static string BLAST_OUTPUT_SUFFIX_DEFAULT {
            get {
                return ResourceManager.GetString("BLAST_OUTPUT_SUFFIX_DEFAULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blast-2.2.25+.
        /// </summary>
        public static string BLAST_VERSION {
            get {
                return ResourceManager.GetString("BLAST_VERSION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blastdb.
        /// </summary>
        public static string BlastDbEnvironmentVariable {
            get {
                return ResourceManager.GetString("BlastDbEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blastn.exe.
        /// </summary>
        public static string BLASTN {
            get {
                return ResourceManager.GetString("BLASTN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg.
        /// </summary>
        public static string ChartFormat {
            get {
                return ResourceManager.GetString("ChartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to csv.
        /// </summary>
        public static string CsvExtension {
            get {
                return ResourceManager.GetString("CsvExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string CsvFilename {
            get {
                return ResourceManager.GetString("CsvFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,Value,Minimum,Maximum,Mean.
        /// </summary>
        public static string CsvHeader {
            get {
                return ResourceManager.GetString("CsvHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Reads.
        /// </summary>
        public static string CsvNumReads {
            get {
                return ResourceManager.GetString("CsvNumReads", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phred Base Quality Score (Min/Max/Mean).
        /// </summary>
        public static string CsvPhredBaseQualityScore {
            get {
                return ResourceManager.GetString("CsvPhredBaseQualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phred Read Quality Score (Min/Max/Mean).
        /// </summary>
        public static string CsvPhredReadQualityScore {
            get {
                return ResourceManager.GetString("CsvPhredReadQualityScore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GC % Content by Read (Min/Max/Mean).
        /// </summary>
        public static string CsvReadGcContent {
            get {
                return ResourceManager.GetString("CsvReadGcContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Lengths (Min/Max/Mean).
        /// </summary>
        public static string CsvReadLength {
            get {
                return ResourceManager.GetString("CsvReadLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ,.
        /// </summary>
        public static string Delimiter {
            get {
                return ResourceManager.GetString("Delimiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the format (case-sensitive) [only support FastQ and FastA] or type &apos;exit&apos;: .
        /// </summary>
        public static string EnterFormatPrompt {
            get {
                return ResourceManager.GetString("EnterFormatPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found..
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GCContentBySequence.
        /// </summary>
        public static string GCContentBySequenceKeyword {
            get {
                return ResourceManager.GetString("GCContentBySequenceKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format. Please try again..
        /// </summary>
        public static string InvalidFileFormatMessage {
            get {
                return ResourceManager.GetString("InvalidFileFormatMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityScoreByPosition.
        /// </summary>
        public static string QualityScoreByPositionKeyword {
            get {
                return ResourceManager.GetString("QualityScoreByPositionKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QualityScoreBySequence.
        /// </summary>
        public static string QualityScoreBySequenceKeyword {
            get {
                return ResourceManager.GetString("QualityScoreBySequenceKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality score is out of the range of the specified FASTQ format..
        /// </summary>
        public static string QualityScoreOutOfRange {
            get {
                return ResourceManager.GetString("QualityScoreOutOfRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SequenceLengthDistribution.
        /// </summary>
        public static string SequenceLengthDistributionKeyword {
            get {
                return ResourceManager.GetString("SequenceLengthDistributionKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SymbolCountByPosition.
        /// </summary>
        public static string SymbolCountByPositionKeyword {
            get {
                return ResourceManager.GetString("SymbolCountByPositionKeyword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniVec.
        /// </summary>
        public static string UniVec {
            get {
                return ResourceManager.GetString("UniVec", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UniVec_Core.
        /// </summary>
        public static string UniVec_Core {
            get {
                return ResourceManager.GetString("UniVec_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to xml.
        /// </summary>
        public static string XmlExtension {
            get {
                return ResourceManager.GetString("XmlExtension", resourceCulture);
            }
        }
    }
}
