//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.239
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeqcosGui.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SeqcosGui.Properties.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to http://seqcos.codeplex.com.
        /// </summary>
        internal static string ApplicationUri {
            get {
                return ResourceManager.GetString("ApplicationUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to auto-detect the parser type of this file. Please manually set the parser type before continuing..
        /// </summary>
        internal static string AUTOPARSE_FAIL {
            get {
                return ResourceManager.GetString("AUTOPARSE_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nhr.
        /// </summary>
        internal static string BlastDbDnaHeaderExt {
            get {
                return ResourceManager.GetString("BlastDbDnaHeaderExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nin.
        /// </summary>
        internal static string BlastDbDnaIndexExt {
            get {
                return ResourceManager.GetString("BlastDbDnaIndexExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to nsq.
        /// </summary>
        internal static string BlastDbDnaSequenceExt {
            get {
                return ResourceManager.GetString("BlastDbDnaSequenceExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to blastdb.
        /// </summary>
        internal static string BlastDbEnvironmentVariable {
            get {
                return ResourceManager.GetString("BlastDbEnvironmentVariable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BLAST DNA Database index file (*.nin)|*.nin.
        /// </summary>
        internal static string BlastDbFilters {
            get {
                return ResourceManager.GetString("BlastDbFilters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing the database file {0}. Please make sure your BLAST database is properly formatted using formatdb.exe..
        /// </summary>
        internal static string BlastDbNotFound {
            get {
                return ResourceManager.GetString("BlastDbNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phr.
        /// </summary>
        internal static string BlastDbProteinHeaderExt {
            get {
                return ResourceManager.GetString("BlastDbProteinHeaderExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pin.
        /// </summary>
        internal static string BlastDbProteinIndexExt {
            get {
                return ResourceManager.GetString("BlastDbProteinIndexExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to psq.
        /// </summary>
        internal static string BlastDbProteinSequenceExt {
            get {
                return ResourceManager.GetString("BlastDbProteinSequenceExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel this process? .
        /// </summary>
        internal static string CancelConfirm {
            get {
                return ResourceManager.GetString("CancelConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to jpg.
        /// </summary>
        internal static string ChartFormat {
            get {
                return ResourceManager.GetString("ChartFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to exit the program?.
        /// </summary>
        internal static string CloseConfirm {
            get {
                return ResourceManager.GetString("CloseConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string DB_SELECT_FAIL {
            get {
                return ResourceManager.GetString("DB_SELECT_FAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discarded {0}/{1} sequences..
        /// </summary>
        internal static string DiscardReport {
            get {
                return ResourceManager.GetString("DiscardReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to explorer.exe.
        /// </summary>
        internal static string Explorer {
            get {
                return ResourceManager.GetString("Explorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid output parser type. Unable to continue..
        /// </summary>
        internal static string InvalidOutputParserType {
            get {
                return ResourceManager.GetString("InvalidOutputParserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No appropriate image files were found in this directory..
        /// </summary>
        internal static string LoadRunFail {
            get {
                return ResourceManager.GetString("LoadRunFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results Found.
        /// </summary>
        internal static string LoadRunFailCaption {
            get {
                return ResourceManager.GetString("LoadRunFailCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose one....
        /// </summary>
        internal static string MANUAL_CHOICE {
            get {
                return ResourceManager.GetString("MANUAL_CHOICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an input filename..
        /// </summary>
        internal static string NoInputFile {
            get {
                return ResourceManager.GetString("NoInputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an input parser type..
        /// </summary>
        internal static string NoInputParserType {
            get {
                return ResourceManager.GetString("NoInputParserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oops...something wrong happened. The program shouldn&apos;t have reached here..
        /// </summary>
        internal static string NonsenseError {
            get {
                return ResourceManager.GetString("NonsenseError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output filename..
        /// </summary>
        internal static string NoOutputFile {
            get {
                return ResourceManager.GetString("NoOutputFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select an output parser type..
        /// </summary>
        internal static string NoOutputParserType {
            get {
                return ResourceManager.GetString("NoOutputParserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a non-numeric value in a numeric field. Please correct this..
        /// </summary>
        internal static string NotNumeric {
            get {
                return ResourceManager.GetString("NotNumeric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have entered a non-positive integer value. Please correct this..
        /// </summary>
        internal static string NotPositiveInteger {
            get {
                return ResourceManager.GetString("NotPositiveInteger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to process the regular expression pattern {0}. Please try again..
        /// </summary>
        internal static string NotValidRegex {
            get {
                return ResourceManager.GetString("NotValidRegex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a value in all required fields..
        /// </summary>
        internal static string NoValue {
            get {
                return ResourceManager.GetString("NoValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We believe the selected read length is greater than the current maximum read length ({0} bp) for the input file {1}. Do you wish to continue with the filtering? Click Cancel to go back and make changes..
        /// </summary>
        internal static string ReadLengthTooLarge {
            get {
                return ResourceManager.GetString("ReadLengthTooLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is the read length too large?.
        /// </summary>
        internal static string ReadLengthTooLargeCaption {
            get {
                return ResourceManager.GetString("ReadLengthTooLargeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have selected the same filename in more than one field. Please choose a different filename..
        /// </summary>
        internal static string SameFilename {
            get {
                return ResourceManager.GetString("SameFilename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trimmed {0}/{1} sequences..
        /// </summary>
        internal static string TrimReport {
            get {
                return ResourceManager.GetString("TrimReport", resourceCulture);
            }
        }
    }
}
